/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServerComponentRouteImport } from './routes/serverComponent'
import { Route as CompositeComponentRouteImport } from './routes/compositeComponent'
import { Route as IndexRouteImport } from './routes/index'

const ServerComponentRoute = ServerComponentRouteImport.update({
  id: '/serverComponent',
  path: '/serverComponent',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositeComponentRoute = CompositeComponentRouteImport.update({
  id: '/compositeComponent',
  path: '/compositeComponent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compositeComponent': typeof CompositeComponentRoute
  '/serverComponent': typeof ServerComponentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compositeComponent': typeof CompositeComponentRoute
  '/serverComponent': typeof ServerComponentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compositeComponent': typeof CompositeComponentRoute
  '/serverComponent': typeof ServerComponentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compositeComponent' | '/serverComponent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compositeComponent' | '/serverComponent'
  id: '__root__' | '/' | '/compositeComponent' | '/serverComponent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompositeComponentRoute: typeof CompositeComponentRoute
  ServerComponentRoute: typeof ServerComponentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/serverComponent': {
      id: '/serverComponent'
      path: '/serverComponent'
      fullPath: '/serverComponent'
      preLoaderRoute: typeof ServerComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compositeComponent': {
      id: '/compositeComponent'
      path: '/compositeComponent'
      fullPath: '/compositeComponent'
      preLoaderRoute: typeof CompositeComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompositeComponentRoute: CompositeComponentRoute,
  ServerComponentRoute: ServerComponentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
